SAURABH| fix url logo and themes
Walkover-Web-Solution/hitman-ui pull request #306
Opened 2024-06-01 07:15 UTC by Saurabh186

2024-06-01 07:31 UTC, idris-bohra commented on src/components/collectionVersions/collectionParentPages.jsx
> +import React, { Component, useState } from 'react'
why useState in react classbased component

2024-06-01 07:44 UTC, idris-bohra commented on src/components/collectionVersions/collectionParentPages.jsx
> +    const staticColor = '#bdbdbd';
Add this as a enum and also make the variable of this color in scss

2024-06-01 07:45 UTC, idris-bohra commented on src/components/endpoints/displayEndpoint.jsx
> +    const staticColor = '#f5f5f5';
Also make this color in scss and enums file

2024-06-01 07:46 UTC, idris-bohra commented on src/components/endpoints/displayEndpoint.jsx
> +  render(props) {
remove this if not used and if used then rename this

2024-06-01 07:47 UTC, idris-bohra commented on src/components/endpoints/displayResponse.jsx
> +    const staticColor = '#fafafa';
Add the variable Enum and scss

2024-06-01 07:47 UTC, idris-bohra commented on src/components/endpoints/endpoints.jsx
> +    const staticColor = '#bdbdbd';
??

2024-06-01 07:47 UTC, idris-bohra commented on src/components/endpoints/endpoints.scss
> +    border: 1px solid #0000001f;
0000001f make this as variable in scss

2024-06-01 07:48 UTC, idris-bohra commented on src/components/endpoints/genericTable.jsx
> +    const staticColor = '#fafafa';
Enum and scss variable

2024-06-01 07:48 UTC, idris-bohra commented on src/components/endpoints/publicBodyContainer.jsx
> +    const staticColor = '#fafafa';
Enum and scss var

2024-06-01 07:49 UTC, idris-bohra commented on src/components/endpoints/publicSampleResponse.jsx
> +    const staticColor = '#fafafa';
Enum and scss var

2024-06-01 07:49 UTC, idris-bohra commented on src/components/main/main.scss
> +  border: 1px solid #0000001f;
Enum and scss var

2024-06-01 07:49 UTC, idris-bohra commented on src/components/main/sidebar.scss
> +  background: #0000001f;
Enum and scss var

2024-06-01 07:49 UTC, idris-bohra commented on src/components/main/sidebar.scss
> +  border: 1px solid #0000001f;
Enum and scss var

2024-06-01 07:49 UTC, idris-bohra commented on src/components/main/sidebar.scss
> +  border-top: 1px solid #0000001f;
Enum and scss var

2024-06-01 07:51 UTC, idris-bohra requested changes
Hover on subPage and give more padding to the subpage and parent page same as the collection.

Restore the hover of expand and collapse icon.

2024-06-03 07:24 UTC, Saurabh186 commented on src/components/collectionVersions/collectionParentPages.jsx
> +import React, { Component, useState } from 'react'
done

2024-06-03 07:24 UTC, Saurabh186 commented on src/components/collectionVersions/collectionParentPages.jsx
> +    const staticColor = '#bdbdbd';
done

2024-06-03 07:24 UTC, Saurabh186 commented on src/components/endpoints/displayEndpoint.jsx
> +    const staticColor = '#f5f5f5';
done

2024-06-03 07:26 UTC, Saurabh186 commented on src/components/endpoints/displayEndpoint.jsx
> +  render(props) {
dome

2024-06-03 07:26 UTC, Saurabh186 commented on src/components/endpoints/displayResponse.jsx
> +    const staticColor = '#fafafa';
done

2024-06-03 07:26 UTC, Saurabh186 commented on src/components/endpoints/endpoints.jsx
> +    const staticColor = '#bdbdbd';
done

2024-06-03 07:27 UTC, Saurabh186 commented on src/components/endpoints/endpoints.scss
> +    border: 1px solid #0000001f;
done

2024-06-03 07:27 UTC, Saurabh186 commented on src/components/endpoints/genericTable.jsx
> +    const staticColor = '#fafafa';
done

2024-06-03 07:27 UTC, Saurabh186 commented on src/components/endpoints/publicBodyContainer.jsx
> +    const staticColor = '#fafafa';
done

2024-06-03 07:27 UTC, Saurabh186 commented on src/components/endpoints/publicSampleResponse.jsx
> +    const staticColor = '#fafafa';
done

2024-06-03 07:27 UTC, Saurabh186 commented on src/components/main/main.scss
> +  border: 1px solid #0000001f;
done

2024-06-03 07:27 UTC, Saurabh186 commented on src/components/main/sidebar.scss
> +  background: #0000001f;
done

2024-06-03 07:28 UTC, Saurabh186 commented on src/components/main/sidebar.scss
> +  border: 1px solid #0000001f;
done

2024-06-03 07:28 UTC, Saurabh186 commented on src/components/main/sidebar.scss
> +  border-top: 1px solid #0000001f;
done

2024-06-03 09:53 UTC, idris-bohra requested changes

2024-06-03 10:17 UTC, idris-bohra approved these changes

2024-06-03 11:09 UTC, merged